@startuml Add a Booking

header Bookings System Sequence Diagram
footer Page %page% of %lastpage%
title "Add a Booking (POST)"

participant "Client" as client
participant "<<javaScript>>\n:Server" as server
participant "<<middleware>>\n:AuthMiddleware" as authMiddleware
participant "<<router>>\n:Bookings" as bookingsRouter
participant "<<controllers>>\n:Booking" as bookingController
database "<<MongoDB>>\n:BookingsDB" as BookingsDatabase

client->server ++: POST /bookings
server->authMiddleware ++: protect, authorize("user", "admin")
authMiddleware --> server --: User authenticated and authorized
server->bookingsRouter ++: Route to Bookings
bookingsRouter->bookingController ++: addBooking()
bookingController->BookingsDatabase ++: Create new booking
BookingsDatabase --> bookingController --: Return new booking
bookingController-->client --: Response with new booking

@enduml
