@startuml Get All Campgrounds

header Campgrounds Booking System Sequence Diagram
footer Page %page% of %lastpage%
title "Get All Campgrounds (GET)"

participant "Client" as client
participant "<<javaScript>>\n:Server" as server
participant "<<router>>\n:Campgrounds" as campgroundsRouter
participant "<<controllers>>\n:Campground" as campgroundController
database "<<MongoDB>>\n:CampgroundsDB" as CampgroundsDatabase

client->server ++: GET /campgrounds
server->campgroundsRouter ++: Route to Campgrounds
campgroundsRouter->campgroundController ++: getCampgrounds()
campgroundController->CampgroundsDatabase ++: Query all campgrounds
CampgroundsDatabase-->campgroundController --: Return campgrounds list
campgroundController-->client --: Response with campgrounds list

@enduml
